######################################
#
# guitarmidi-lv2
#
######################################

# where to find the source code - locally in this case
GUITARMIDI_LV2_SITE_METHOD = local
GUITARMIDI_LV2_SITE = /home/gerald/workspace/src/GuitarMidi-LV2

# even though this is a local build, we still need a version number
# bump this number if you need to force a rebuild
GUITARMIDI_LV2_VERSION = v2.0

# dependencies (list of other buildroot packages, separated by space)
# commercial plugins require libmodla as dependency
GUITARMIDI_LV2_DEPENDENCIES = libmodla

# LV2 bundles generated by this package (space separated list)
GUITARMIDI_LV2_BUNDLES = guitarmidi.lv2


# call make with the current arguments and path. "$(@D)" is the build directory.
GUITARMIDI_LV2_TARGET_MAKE = $(TARGET_MAKE_ENV) $(TARGET_CONFIGURE_OPTS) $(MAKE) -C $(@D)/hardware/moddevices DESTDIR=$(TARGET_DIR) 

# build command
define GUITARMIDI_LV2_BUILD_CMDS
	$(GUITARMIDI_LV2_TARGET_MAKE) guitarmidi.so
endef

# install command
define GUITARMIDI_LV2_INSTALL_TARGET_CMDS
	$(GUITARMIDI_LV2_TARGET_MAKE) install 
endef

# import everything else from the buildroot generic package
$(eval $(generic-package))
