name: Build and Test LV2 Plugin

# Define the events that trigger this workflow
on:
  push:
    branches:
      - master  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - master  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-22.04  # Specify the OS to run the job on

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3  # Use the checkout action to clone the repository

    # # Step 2: Set up CMake
    # - name: Set up CMake
    #   uses: threeal/cmake-action@main

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update  
        sudo apt-get install -y cmake pango1.0-tools libpango1.0-dev pkg-config libomp-dev  

    # Step 4: Configure the project using CMake
    - name: Configure CMake
      run: cmake -B build -S .  # Configure the project, specifying the build directory

    # Step 5: Build the project
    - name: Build
      run: cmake --build build -- -j$(nproc)  # Build the project using all available processors


