name: Build and Test LV2 Plugin

# Define the events that trigger this workflow
on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-22.04  # Specify the OS to run the job on

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3  # Use the checkout action to clone the repository

    # Step 2: Set up CMake
    - name: Set up CMake
      uses: lukka/get-cmake@v3  # Use the lukka/get-cmake action to install CMake

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update  # Update the package list
        sudo apt-get install -y \
          pango1.0-tools \  # Install Pango tools
          libpango1.0-dev \  # Install Pango development libraries
          pkg-config \  # Install pkg-config
          libomp-dev  # Install OpenMP development libraries

    # Step 4: Configure the project using CMake
    - name: Configure CMake
      run: cmake -B build -S .  # Configure the project, specifying the build directory

    # Step 5: Build the project
    - name: Build
      run: cmake --build build -- -j$(nproc)  # Build the project using all available processors


